#!/bin/bash
# Script Installer
# Dibuat oleh: FREETUNNELING

# --- Definisi Warna ---
NC='\033[0m' # No Color
BIBlack='\033[1;90m'
BIRed='\033[1;91m'
BIGreen='\033[1;92m'
BIYellow='\033[1;93m'
BIBlue='\033[1;94m'
BIPurple='\033[1;95m'
BICyan='\033[1;96m'
BIWhite='\033[1;97m'
UWhite='\033[4;37m'
On_IPurple='\033[0;105m'
On_IRed='\033[0;101m'
IBlack='\033[0;90m'
IRed='\033[0;91m'
IGreen='\033[0;92m'
IYellow='\033[0;93m'
IBlue='\033[0;94m'
IPurple='\033[0;95m'
ICyan='\033[0;96m'
IWhite='\033[0;97m'
BGCOLOR='\e[1;97;101m' # WHITE RED
repo="https://raw.githubusercontent.com/freetunnel/bal/main/"
# Definisi warna singkat (jika diperlukan, untuk konsistensi)
red='\e[1;31m'
green='\e[0;32m'
yell='\e[1;33m'
tyblue='\e[1;36m'
# GREEN dan CYAN sudah didefinisikan di atas, jadi tidak perlu duplikasi.
export PINK='\033[0;35m'
export YELLOW='\033[0;33m'

# --- Fungsi Warna Teks ---
purple() { echo -e "\033[35;1m${*}\033[0m"; }
tyblue() { echo -e "\033[36;1m${*}\033[0m"; }
yellow() { echo -e "\033[33;1m${*}\033[0m"; }
green() { echo -e "\033[32;1m${*}\033[0m"; }
red() { echo -e "\033[31;1m${*}\033[0m"; }

# --- Validasi Awal ---
echo -e "${GREEN}♻️ Check Validasi Masuk...${NC}"
sleep 3
clear

# Pastikan direktori yang dibutuhkan ada
mkdir -p /etc/data

# --- Mendapatkan IP Publik Pengguna ---
user_ip=$(curl -s https://ipinfo.io/ip)

echo -e "${GREEN}Sedang Melanjutkan proses...${NC}"
sleep 2

echo -e "${GREEN}Mengunduh dan menginstal dependensi...${NC}"
sleep 2

clear

# --- Validasi Root Access ---
if [[ "${EUID}" -ne 0 ]]; then
    red "Script harus dijalankan sebagai user root!"
    exit 1
fi

# --- Validasi Virtualisasi ---
if [[ "$(systemd-detect-virt)" == "openvz" ]]; then
    red "OpenVZ tidak didukung!"
    exit 1
fi

# --- Konfigurasi Hostname ---
cd /root || exit 1
local_ip=$(hostname -I | cut -d' ' -f1)
host_name=$(hostname)

# Perbaiki file hosts jika diperlukan
if ! grep -q "^${local_ip} ${host_name}" /etc/hosts; then
    echo "${local_ip} ${host_name}" >> /etc/hosts
fi

# --- Fungsi Konversi Waktu ---
secs_to_human() {
    local jam=$(( $1 / 3600 ))
    local menit=$(( ($1 % 3600) / 60 ))
    local detik=$(( $1 % 60 ))
    echo "Waktu instalasi: ${jam} jam ${menit} menit ${detik} detik"
}

# --- Persiapan Direktori ---
rm -rf /etc/rmbl
mkdir -p /etc/rmbl
mkdir -p /etc/rmbl/theme
mkdir -p /var/lib/ >/dev/null 2>&1
mkdir /etc/kuota-ssh
echo "IP=" >> /var/lib/ipvps.conf
clear

# --- Input Nama Pengguna ---
echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
echo -e "${BIBlue}│ ${BGCOLOR}      MASUKKAN NAMA KAMU           ${NC}${BIBlue} │${NC}"
echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
echo " "
until [[ $name =~ ^[a-zA-Z0-9_.-]+$ ]]; do
    read -rp "Masukan Nama Kamu Disini tanpa spasi : " -e name
done
rm -rf /etc/profil
echo "$name" > /etc/profil
echo ""
clear
author=$(cat /etc/profil)
echo ""
echo ""

# --- Fungsi Bar Progres (fun_bar) ---
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[0;33mUpdate Domain.. \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;33mUpdate Domain... \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m Succes !\033[1;37m"
    tput cnorm
}

clear
cd

# --- Pilihan Domain ---
res99() {
wget ${repo}tools/ftp.sh&& chmod +x ftp.sh&& ./ftp.sh
clear
}
clear
cd
echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
echo -e "${BIBlue}│ \033[1;37mPlease select a your Choice to Set Domain${BIBlue}│${NC}"
echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
echo -e "${BIBlue}│  [ 1 ]  \033[1;37mDomain kamu sendiri       ${NC}"
echo -e "${BIBlue}│  [ 2 ]  \033[1;37mDomain yang punya script  ${NC}"
echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
until [[ $domain =~ ^[132]+$ ]]; do 
read -p "   Please select numbers 1  atau 2 : " domain
done
if [[ $domain == "1" ]]; then
clear
echo -e  "${BIBlue}╭══════════════════════════════════════════╮${NC}"
echo -e  "${BIBlue}│              \033[1;37mTERIMA KASIH                ${BIBlue}│${NC}"
echo -e  "${BIBlue}│         \033[1;37mSUDAH MENGGUNAKAN SCRIPT         ${BIBlue}│${NC}"
echo -e  "${BIBlue}│                \033[1;37m FREETUNNELING                 ${BIBlue}│${NC}"
echo -e  "${BIBlue}╰══════════════════════════════════════════╯${NC}"
echo " "
until [[ $dnss =~ ^[a-zA-Z0-9_.-]+$ ]]; do 
read -rp "Masukan domain kamu Disini : " -e dnss
done
rm -rf /etc/xray
rm -rf /etc/v2ray
rm -rf /etc/nsdomain
rm -rf /etc/per
mkdir -p /etc/xray
mkdir -p /etc/v2ray
mkdir -p /etc/nsdomain
touch /etc/xray/domain
touch /etc/v2ray/domain
touch /etc/xray/slwdomain
touch /etc/v2ray/scdomain
echo "$dnss" > /root/domain
echo "$dnss" > /root/scdomain
echo "$dnss" > /etc/xray/scdomain
echo "$dnss" > /etc/v2ray/scdomain
echo "$dnss" > /etc/xray/domain
echo "$dnss" > /etc/v2ray/domain
echo "IP=$dnss" > /var/lib/ipvps.conf
echo ""
cd
sleep 1
clear
rm /root/subdomainx
clear
fi
if [[ $domain == "2" ]]; then
clear
echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
echo -e "${BIBlue}│ \033[1;37mPlease select a your Choice to Set Domain${BIBlue}│${NC}"
echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
echo -e "${BIBlue}│  [ 1 ]  \033[1;37mDomain xxx.freetinnel.net         ${NC}"                                        
echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
until [[ $domain2 =~ ^[1-5]+$ ]]; do 
read -p "   Please select numbers 1 sampai 1 : " domain2
done
fi
if [[ $domain2 == "1" ]]; then
clear
echo -e  "${BIBlue}╭══════════════════════════════════════════╮${NC}"
echo -e  "${BIBlue}│  \033[1;37mContoh subdomain xxx.freetinnel.net       ${BIBlue}│${NC}"
echo -e  "${BIBlue}│    \033[1;37mxxx jadi subdomain kamu               ${BIBlue}│${NC}"
echo -e  "${BIBlue}╰══════════════════════════════════════════╯${NC}"
echo " "
until [[ $dn1 =~ ^[a-zA-Z0-9_.-]+$ ]]; do
read -rp "Masukan subdomain kamu Disini tanpa spasi : " -e dn1
done
rm -rf /etc/xray
rm -rf /etc/v2ray
rm -rf /etc/nsdomain
rm -rf /etc/per
mkdir -p /etc/xray
mkdir -p /etc/v2ray
mkdir -p /etc/nsdomain
mkdir -p /etc/per
touch /etc/per/id
touch /etc/per/token
touch /etc/xray/domain
touch /etc/v2ray/domain
touch /etc/xray/slwdomain
touch /etc/v2ray/scdomain
echo "$dn1" > /root/subdomainx
cd
sleep 1
fun_bar 'res99'
clear
rm /root/subdomainx
fi
# --- Daftar Tema Warna ---
cat <<EOF>> /etc/rmbl/theme/green
BG : \E[40;1;42m
TEXT : \033[0;32m
EOF
cat <<EOF>> /etc/rmbl/theme/yellow
BG : \E[40;1;43m
TEXT : \033[0;33m
EOF
cat <<EOF>> /etc/rmbl/theme/red
BG : \E[40;1;41m
TEXT : \033[0;31m
EOF
cat <<EOF>> /etc/rmbl/theme/blue
BG : \E[40;1;44m
TEXT : \033[0;34m
EOF
cat <<EOF>> /etc/rmbl/theme/magenta
BG : \E[40;1;45m
TEXT : \033[0;35m
EOF
cat <<EOF>> /etc/rmbl/theme/cyan
BG : \E[40;1;46m
TEXT : \033[0;36m
EOF
cat <<EOF>> /etc/rmbl/theme/lightgray
BG : \E[40;1;47m
TEXT : \033[0;37m
EOF
cat <<EOF>> /etc/rmbl/theme/darkgray
BG : \E[40;1;100m
TEXT : \033[0;90m
EOF
cat <<EOF>> /etc/rmbl/theme/lightred
BG : \E[40;1;101m
TEXT : \033[0;91m
EOF
cat <<EOF>> /etc/rmbl/theme/lightgreen
BG : \E[40;1;102m
TEXT : \033[0;92m
EOF
cat <<EOF>> /etc/rmbl/theme/lightyellow
BG : \E[40;1;103m
TEXT : \033[0;93m
EOF
cat <<EOF>> /etc/rmbl/theme/lightblue
BG : \E[40;1;104m
TEXT : \033[0;94m
EOF
cat <<EOF>> /etc/rmbl/theme/lightmagenta
BG : \E[40;1;105m
TEXT : \033[0;95m
EOF
cat <<EOF>> /etc/rmbl/theme/lightcyan
BG : \E[40;1;106m
TEXT : \033[0;96m
EOF
cat <<EOF>> /etc/rmbl/theme/color.conf
lightcyan
EOF

# Set tema default ke cyan
echo "cyan" > /etc/rmbl/theme/color.conf

# --- Disable IPv6 ---
echo -e "${GREEN}Mematikan IPv6...${NC}"
sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1
sysctl -w net.ipv6.conf.default.disable_ipv6=1 >/dev/null 2>&1
echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
sysctl -p >/dev/null 2>&1

# --- Disable AppArmor (Ubuntu 24.04) ---
echo -e "${GREEN}Mematikan AppArmor...${NC}"
systemctl disable --now apparmor >/dev/null 2>&1
systemctl stop apparmor >/dev/null 2>&1
update-rc.d -f apparmor remove >/dev/null 2>&1 # Ini mungkin tidak ada di semua sistem, tapi aman.
apt-get purge apparmor apparmor-utils -y >/dev/null 2>&1

clear

# --- Instalasi Tools Awal ---
wget https://raw.githubusercontent.com/freetunnel/bal/main/tools/tools.sh -O tools.sh &> /dev/null
chmod +x tools.sh
bash tools.sh
start=$(date +%s)
ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

# --- Update dan Instal Dependensi Umum untuk Ubuntu 24.04 ---
echo -e "${GREEN}Memperbarui sistem dan menginstal dependensi...${NC}"
apt update -y && apt upgrade -y
apt install git curl python3 apt  figlet python3-pip apt-transport-https ca-certificates software-properties-common ntpdate wget netcat-openbsd ncurses-bin chrony jq -y
-y
wget https://github.com/fullstorydev/grpcurl/releases/download/v1.9.1/grpcurl_1.9.1_linux_x86_64.tar.gz -O /tmp/grpcurl.tar.gz && tar -xzf /tmp/grpcurl.tar.gz -C /tmp/ && sudo mv /tmp/grpcurl /usr/local/bin/ && sudo chmod +x /usr/local/bin/grpcurl
wget https://raw.githubusercontent.com/XTLS/Xray-core/main/app/stats/command/command.proto -O stats.proto

cd
clear
wget https://raw.githubusercontent.com/freetunnel/bal/main/toola/limit.sh -O limit.sh && chmod +x limit.sh && ./limit.sh
clear

# --- Fungsi Instalasi Modul ---
res3() {
    echo -e "${GREEN}    Memulai instalasi SSH WS / OpenVPN...${NC}"
    wget https://raw.githubusercontent.com/freetunnel/bal/main/system/ssh-vpn.sh -O ssh-vpn.sh
    chmod +x ssh-vpn.sh
    ./ssh-vpn.sh
    sudo systemctl enable --now chrony.service
    sudo systemctl restart chrony.service
    clear
}

res4() {
    echo -e "${GREEN}    Memulai instalasi XRAY...${NC}"
    wget https://raw.githubusercontent.com/freetunnel/bal/main/system/ins-xray.sh -O ins-xray.sh
    chmod +x ins-xray.sh
    ./ins-xray.sh
    clear
}

res5() {
    echo -e "${GREEN}    Memulai instalasi WEBSOCKET SSH...${NC}"
    wget https://raw.githubusercontent.com/freetunnel/bal/main/websocket/insshws.sh -O insshws.sh
    chmod +x insshws.sh
    ./insshws.sh
    clear
}

res6() {
    echo -e "${GREEN}    Memulai instalasi BACKUP MENU...${NC}"
    wget https://raw.githubusercontent.com/freetunnel/bal/main/system/set-br.sh -O set-br.sh
    chmod +x set-br.sh
    ./set-br.sh
    clear
}

res7() {
    echo -e "${GREEN}    Memulai instalasi OHP...${NC}"
    wget https://raw.githubusercontent.com/freetunnel/bal/main/websocket/ohp.sh -O ohp.sh
    chmod +x ohp.sh
    ./ohp.sh
    clear
}

res8() {
    echo -e "${GREEN}    Memulai pengunduhan EXTRA MENU...${NC}"
    wget https://raw.githubusercontent.com/freetunnel/bal/main/menu/update.sh -O update.sh
    chmod +x update.sh
    ./update.sh
    clear
}

res9() {
    echo -e "${GREEN}    Memulai pengunduhan SLOWDNS...${NC}"
    wget https://raw.githubusercontent.com/freetunnel/bal/main/slowdns/sld.sh -O sld.sh
    chmod +x sld.sh
    ./sld.sh
    clear
}

res10() {
    echo -e "${GREEN}    Memulai pengunduhan UDP CUSTOM...${NC}"
    mkdir -p /usr/local/kyt/
    wget -q -O /usr/local/kyt/udp-mini "${REPO}Fls/udp-mini"
     chmod +x /usr/local/kyt/udp-mini
    wget https://raw.githubusercontent.com/freetunnel/bal/main/system/udp-custom.sh -O udp-custom.sh
    chmod +x udp-custom.sh
    bash udp-custom.sh
    clear
}

res11() {
    echo -e "${GREEN}    Mengkonfigurasi Dropbear...${NC}"
    apt install dropbear -y
    sudo sed -i '/^DROPBEAR_PORT=/d' /etc/default/dropbear
    sudo sed -i '/^DROPBEAR_EXTRA_ARGS=/d' /etc/default/dropbear
    echo 'DROPBEAR_PORT=149' | sudo tee -a /etc/default/dropbear
    echo 'DROPBEAR_EXTRA_ARGS="-p 50000 -p 109 -p 110 -p 69 -b /etc/issue.net"' | sudo tee -a /etc/default/dropbear

    sudo mkdir -p /etc/dropbear/
    sudo dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
    sudo dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
    sudo chmod 600 /etc/dropbear/dropbear_dss_host_key
    sudo chmod 600 /etc/dropbear/dropbear_rsa_host_key
    sudo chown root:root /etc/dropbear/dropbear_dss_host_key
    sudo chown root:root /etc/dropbear/dropbear_rsa_host_key
    sed -i 's/^NO_START=.*/NO_START=0/' /etc/default/dropbear
    sudo systemctl daemon-reload
    sudo systemctl restart dropbear
     sudo systemctl enable nginx
    clear
}
res12() {
    echo -e "${GREEN}   Mengatur jadwal reboot harian...${NC}"
    
    # Definisikan cron job yang ingin ditambahkan
    REBOOT_JOB="0 0 * * * /sbin/reboot"

    # Periksa apakah cron job tersebut sudah ada
    if ! sudo crontab -l | grep -Fxq "$REBOOT_JOB"; then
        # Jika TIDAK ADA, maka tambahkan
        (sudo crontab -l 2>/dev/null; echo "$REBOOT_JOB") | sudo crontab -
        echo -e "${GREEN}   -> Jadwal reboot otomatis setiap jam 12 malam telah berhasil ditambahkan.${NC}"
    else
        # Jika SUDAH ADA, beri pesan dan jangan lakukan apa-apa
        echo -e "${YELLOW}   -> Jadwal reboot otomatis sudah ada, tidak ada yang diubah.${NC}"
    fi
}
res13() {
    echo -e "${GREEN}    Mengatur jadwal update kuota otomatis...${NC}"
    
# Definisikan cron job yang ingin ditambahkan
USAGE_JOB="*/1 * * * * /usr/bin/update-usage.sh >/dev/null 2>&1"
USAGE_JOB2="*/2 * * * * /usr/bin/update-ssh-usage.sh >/dev/null 2>&1"

# Periksa dan tambahkan jadwal untuk kuota XRAY
    if ! sudo crontab -l | grep -Fxq "$USAGE_JOB"; then
        (sudo crontab -l 2>/dev/null; echo "$USAGE_JOB") | sudo crontab -
        echo -e "${GREEN}    -> Jadwal update kuota xray setiap 1 menit telah berhasil ditambahkan.${NC}"
    else
        echo -e "${YELLOW}    -> Jadwal update kuota xray sudah ada, tidak ada yang diubah.${NC}"
    fi

# Periksa dan tambahkan jadwal untuk kuota SSH
    if ! sudo crontab -l | grep -Fxq "$USAGE_JOB2"; then
    # PERBAIKAN 1: Gunakan variabel $USAGE_JOB2 di sini
        (sudo crontab -l 2>/dev/null; echo "$USAGE_JOB2") | sudo crontab -
    # PERBAIKAN 2: Sesuaikan pesan dengan jadwal (setiap 2 menit)
        echo -e "${GREEN}    -> Jadwal update kuota sshws setiap 2 menit telah berhasil ditambahkan.${NC}"
    else
        echo -e "${YELLOW}    -> Jadwal update kuota sshws sudah ada, tidak ada yang diubah.${NC}"
    fi
}


# --- Proses Instalasi
function Download(){
    echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
    echo -e "${BIBlue}│ ${BGCOLOR}    PROCESS INSTALLED SSH WS / OPENVPN    ${NC}${BIBlue} │${NC}"
    echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
    res3

    echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
    echo -e "${BIBlue}│ ${BGCOLOR}        PROCESS INSTALLED XRAY          ${NC}${BIBlue} │${NC}"
    echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
    res4

    echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
    echo -e "${BIBlue}│ ${BGCOLOR}    PROCESS INSTALLED WEBSOCKET SSH   ${NC}${BIBlue} │${NC}"
    echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
    res5

    echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
    echo -e "${BIBlue}│ ${BGCOLOR}    PROCESS INSTALLED BACKUP MENU     ${NC}${BIBlue} │${NC}"
    echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
    res6

    echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
    echo -e "${BIBlue}│ ${BGCOLOR}        PROCESS INSTALLED OHP         ${NC}${BIBlue} │${NC}"
    echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
    res7

    echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
    echo -e "${BIBlue}│ ${BGCOLOR}        DOWNLOAD EXTRA MENU           ${NC}${BIBlue} │${NC}"
    echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
    res8

    echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
    echo -e "${BIBlue}│ ${BGCOLOR}        DOWNLOAD SLOWDNS              ${NC}${BIBlue} │${NC}"
    echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
    res9

    echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
    echo -e "${BIBlue}│ ${BGCOLOR}        DOWNLOAD UDP COSTUM           ${NC}${BIBlue} │${NC}"
    echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
    res10
    
    echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
    echo -e "${BIBlue}│ ${BGCOLOR}    CONFIGURING DROPBEAR              ${NC}${BIBlue} │${NC}"
    echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
    res11

    echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
    echo -e "${BIBlue}│ ${BGCOLOR}  ATUR JADWAL REBOOT              ${NC}${BIBlue} │${NC}"
    echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
    res12

 echo -e "${BIBlue}╭══════════════════════════════════════════╮${NC}"
    echo -e "${BIBlue}│ ${BGCOLOR} PANTAU PEMAKAIANA KUOTA           ${NC}${BIBlue} │${NC}"
    echo -e "${BIBlue}╰══════════════════════════════════════════╯${NC}"
    res12
}
Download # Memanggil fungsi SKT4100

# --- Konfigurasi Post-Instalasi ---
# Pastikan file /home/re_otm ada dan berikan nilai default jika tidak
if [ ! -f "/home/re_otm" ]; then
    echo "0" > /home/re_otm
fi

cat > /root/.profile << END
if [ "$BASH" ]; then
if [ -f ~/.bashrc ]; then
. ~/.bashrc
fi
fi
mesg n || true
clear
menu
END
chmod 644 /root/.profile

# Bersihkan file log instalasi sebelumnya
if [ -f "/root/log-install.txt" ]; then
    rm /root/log-install.txt > /dev/null 2>&1
fi
if [ -f "/etc/afak.conf" ]; then
    rm /etc/afak.conf > /dev/null 2>&1
fi
if [ ! -f "/etc/log-create-user.log" ]; then
    echo "Log All Account " > /etc/log-create-user.log
fi
history -c

serverV=$( curl -sS https://raw.githubusercontent.com/freetunnel/bal/main/tools/versi )
echo "$serverV" > /opt/.ver

aureb=$(cat /home/re_otm)
b=11
if [ "$aureb" -gt "$b" ]
then
    gg="PM"
else
    gg="AM"
fi
cd

# --- Pengambilan Info Server & Pembersihan File ---
curl -sS ifconfig.me > /etc/myipvps
curl -s ipinfo.io/city?token=75082b4831f909 >> /etc/xray/city
curl -s ipinfo.io/org?token=75082b4831f909 | cut -d " " -f 2-10 >> /etc/xray/isp
rm /root/setup.sh >/dev/null 2>&1
rm /root/slhost.sh >/dev/null 2>&1
rm /root/ssh-vpn.sh >/dev/null 2>&1
rm /root/ins-xray.sh >/dev/null 2>&1
rm /root/insshws.sh >/dev/null 2>&1
rm /root/set-br.sh >/dev/null 2>&1
rm /root/ohp.sh >/dev/null 2>&1
rm /root/update.sh >/dev/null 2>&1
rm /root/slowdns.sh >/dev/null 2>&1
rm /root/udp-custom.sh >/dev/null 2>&1 # Hapus file udp-custom.sh setelah digunakan

# --- Pembuatan Direktori Bot dan Limit ---
rm -rf /etc/bot
mkdir -p /etc/bot
mkdir -p /etc/sf/limit/vmess/ip
mkdir -p /etc/limit/vmess
mkdir -p /etc/vmess/limit/ip
mkdir -p /etc/limit/vless
mkdir -p /etc/sf/limit/vless/ip
mkdir -p /etc/limit/trojan
mkdir -p /etc/sf/limit/trojan/ip
mkdir -p /etc/vmess
mkdir -p /etc/vless
mkdir -p /etc/trojan
touch /etc/bot/.bot.db
touch /etc/vmess/.vmess.db
touch /etc/typexray
touch /etc/waktulock
sudo chmod 755 /home/vps
sudo find /home/vps/public_html -type f -exec chmod 644 {} \;
sudo find /home/vps/public_html -type d -exec chmod 755 {} \;
sudo chown -R www-data:www-data /home/vps/public_html
mkdir -p /etc/kyt/limit/vmess/ip
mkdir -p /etc/kyt/limit/vless/ip
mkdir -p /etc/kyt/limit/trojan/ip
mkdir -p /etc/kyt/limit/ssh/ip
# --- Log Waktu Instalasi ---
secs_to_human "$(($(date +%s) - ${start}))" | tee -a log-install.txt
sleep 3
echo ""
cd

# --- Kirim Pesan Sukses ke Telegram ---
domain=$(cat /etc/xray/domain)
TIMES="10"
CHATID="-1002305290411"
KEY="8093025196:AAHAykxQ3K5TBPNev8ozawCi5pR9N9CpWsE"
URL="https://api.telegram.org/bot$KEY/sendMessage"
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain) 
TIME=$(date '+%d %b %Y')
RAMMS=$(free -m | awk 'NR==2 {print $2}')
MODEL2=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
MYIP=$(curl -sS ipv4.icanhazip.com)
IZIN=$(curl -sS https://raw.githubusercontent.com/freetunnel/iz/main/ip | grep $MYIP | awk '{print $3}' )
d1=$(date -d "$IZIN" +%s)
d2=$(date -d "$today" +%s)
USRSC=$(wget -qO- https://raw.githubusercontent.com/freetunnel/iz/main/ip | grep $MYIP | awk '{print $2}')
EXPSC=$(wget -qO- https://raw.githubusercontent.com/freetunnel/iz/main/ip | grep $MYIP | awk '{print $3}')
TEXT="
<code>⚡───────────────────⚡</code>
<b> INSTALL AUTOSCRIPT PREMIUM</b>
<code>⚡───────────────────⚡</code>
<code>ID    : </code><code>$USRSC</code>
<code>DATE  : </code><code>$TIME</code>
<code>EXP   : </code><code>$EXPSC</code>
<code>ISP   : </code><code>$ISP</code>
<code>SC ID : </code><code>UBUNTU 22-25</code>
<code>⚡───────────────────⚡</code>
<i>Automatic Notification Install Script</i>
"'&reply_markup={"inline_keyboard":[[{"text":"ᴏʀᴅᴇʀ","url":"https://t.me/freetunnel3"},{"text":"JOIN","url":"t.me/ftp_corp"}]]}'

curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
sleep 2

systemctl stop ssh.socket
systemctl disable ssh.socket

systemctl enable ssh
systemctl restart ssh

# --- Selesai Instalasi dan Reboot ---
echo -e "${BIBlue}════════════════════════════════════════${NC}"
echo -e "${BIBlue} Script telah berhasil di install"
rm -rf *
#!/bin/bash
echo -e ""
echo -e "❏━━━━━━━━━━━✦ SYSTEM NOTICE ✦━━━━━━━━━━━❏"
echo -e "\e[1;31M  PLEASE REBOOT THE SERVER \e[0m"
echo -e "\e[1;31M  NEW PORT LOGIN VPS : 200 \e[0m"
echo -e "❏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━❏"
echo -en "\e[1;36m[default y](y/n)?\e[0m > "

# Baca input user
read -r answer

# Cek input
if [[ "$answer" =~ ^[Nn]$ ]]; then
    echo -e "\n❌ Reboot dibatalkan oleh user."
    exit 0
else
    echo -e "\n🔄 Melakukan reboot sistem..."
    sleep 1
    cat /dev/null > ~/.bash_history && history -c
    reboot
fi

